### ISSUE TITLE
Scanning looks very slow.

### ISSUE THREAD

**Issue by paul-nechifor** [paul-nechifor/ohmu#23]

**Comment by dellis23** [comment]
We could potentially use `scandir` rather than `os.listdir` to speed things up.  I believe it would cut the number of system calls needed in half.  It was brought into the python stdlib in 3.5, but can also be installed as a python package: https://github.com/benhoyt/scandir

**Comment by dellis23** [comment]
I have a commit here that uses scandir: https://github.com/paul-nechifor/ohmu/commit/12b0cac7743508e6541d26cd824feb3553afec27

The problem is getting a benchmark out of it.  I have used this commit to cause ohmu to exit as soon as scanning is complete: https://github.com/dellis23/ohmu/commit/47c0ecca66ee69b34943f0468216cd19a903c095 .  Timing the run of the same directory multiple times, the total run time had a lot of variance.  I'm assuming filesystem cache is affecting this.  Basically, I don't see the clear improvement I had hoped for.

**Comment by dellis23** [comment]
Not sure how I managed to push that first commit directly to the main repository though...

**Comment by paul-nechifor** [comment]
I've copied that one commit: https://github.com/paul-nechifor/ohmu/commit/44ff94716a4a72bfd7418f67bf7c8b03583d5947 .

**Comment by dellis23** [comment]
Did it appear to be any faster for you @paul-nechifor ?

**Comment by paul-nechifor** [comment]
Yep. (Sorry for replying so late.)

**Comment by dellis23** [comment]
Cool!  Better late that never.
